name: Blog info of Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: styunlen/social-readme@master
        with:
          blog_rss_link: https://styunlen.cn/feed    #your blog rss link
          blog_limit: 5 # blog数量
          douban_name: syunlen
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated blog info # commit说明
